# Sidebar navigation

- label: '2021年7月度定例会のご案内'
  link: '/'
- label: 'Video'
  items:
    - label: '2021年度7月度 本社定例会（録画）'
      link: '/video/recorded-monthly-meeting'
    - label: '目標振り返りワーク説明'
      link: '/video/work-description-of-reflection'
    - label: 'まだ目標設定を行っていない方へ'
      link: '/video/one-one-movie-by-ceo'
- label: '要提出内容'
  items:
    - label: '定例会に参加できた方へ'
      link: '/to-be-submission/able-to-attend'
    - label: '定例会に参加できなかった方へ'
      link: '/to-be-submission/could-not-attend'
- label: '後日ワークショップ'
  items:
    - label: '後日グループディスカッションスケジュール'
      link: '/group-discussion-at-later/schedule'
